create table public.gempa_live (
  id bigint generated by default as identity not null,
  source text null,
  magnitude double precision null,
  wilayah text null,
  waktu text null,
  kedalaman text null,
  koordinat text null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint gempa_live_pkey primary key (id),
  constraint unique_earthquake unique (waktu, koordinat)
) TABLESPACE pg_default;